recordmovies_index:
    path:     /
    defaults: { _controller: "AppBundle:RecordMovies:index" }
    methods:  GET

recordmovies_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RecordMovies:show" }
    methods:  GET



