<?php

namespace AppBundle\Entity;

/**
 * RecordMoviesRepository
 * @author Anthony
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordMoviesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * addRecordMovies function.
     * Ajout d'une fiche de film
     * @access public
     * @param string $title
     * @param string $realisator (default: null)
     * @return id de l'entity créée
     */
    public function addRecordMovies($title, $realisator = null)
    {
        $recordMovie = new RecordMovies($title, $realisator);
        $this->_em->persist($recordMovie);
        $this->_em->flush();
        return $recordMovie->getId();
    }
}
