<?php

namespace AppBundle\Entity;

/**
 * RecordMoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordMoviesRepository extends \Doctrine\ORM\EntityRepository
{
}
